import dns from 'dns/promises';

dns.setServers(["8.8.8.8", "8.8.4.4"]);
import { Geist, Geist_Mono, Manrope, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ToastProvider from '@/components/shared/ToastProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const manrope = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
  weight:["400", "600", "700", "800"]
});
export const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight:["400", "600", "700", "800"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SummerCart || HomePage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <main>
          {children}
        </main>
        <Footer/>
        <ToastProvider/>
      </body>
    </html>
  );
}
